name: Build Windows Application

on:
  push:
    branches:
      - main  # Trigger build on push to the main branch
  pull_request:
    branches:
      - main  # Trigger build on pull requests targeting the main branch

jobs:
  build:
    runs-on: windows-latest  # Use the latest Windows runner

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up MinGW-w64
    - name: Set up MinGW-w64
      uses: egor-tensin/setup-mingw@v2
      with:
        platform: x64  # Specify 64-bit platform

    # Compile the C code using MinGW-w64
    - name: Compile C code
      run: |
        # Compile the C code
        x86_64-w64-mingw32-gcc -o bot.exe bot.c -lws2_32 -lpsapi -lcurl -luserenv

    # Run the compiled executable and wait for 10 minutes (600 seconds)
    - name: Run bot.exe and wait 10 minutes
      run: |
        Start-Process -FilePath "bot.exe"
        Start-Sleep -Seconds 600  # Wait for 10 minutes
