name: Run Bot Script as Administrator

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-bot:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run bot.ps1 as Administrator
      run: |
        Start-Process pwsh -ArgumentList "-ExecutionPolicy Bypass -File $PWD\bot.ps1" -Verb runAs
      shell: pwsh
